### ISSUE TITLE
Fix version in about dialog on OS X

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jkotlinski/lsdpatch#13]
```
...
```

Original issue reported on code.google.com by `kotlin...@gmail.com` on 19 Jun 2011 at 10:13

**Comment by Eiyeron** [comment]
Now that the JAR is tagged by Maven at build, is it still relevant? I don't have a Mac around to give it a shot.

**Comment by jkotlinski** [comment]
It’s not important to fix, it’s just a UI annoyance with os x, when you
select menu LSDPatcher/About LSDPatcher it says ”java version 1.0” in
version info

**Comment by jkotlinski** [comment]
closing due to oldness
