### ISSUE TITLE
Merge samples

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jkotlinski/lsdpatch#22]
```
Would be cool to be able to merge samples inside the program.
```

Original issue reported on code.google.com by `kotlin...@gmail.com` on 28 Aug 2011 at 3:58

**Comment by Eiyeron** [comment]
Is it still in the plans? I had a feature idea in an [issue] on Redux involving slicing samples, both issues are pretty similar in terms of feature, they could *eventually* fall under the same sample manipulation feature in the feature?

[issue]: https://github.com/Eiyeron/lsdpatch/issues/55

**Comment by jkotlinski** [comment]
It could probably be closed as not important

**Comment by Eiyeron** [comment]
I guess so, given that `sox` or any audio manipulation software can handle the splitting itself.

**Comment by jkotlinski** [comment]
closed!
