### ISSUE TITLE
versions 3 of LSDJ and older cannot be opened in the latest LSDpatcher

### ISSUE THREAD

**Issue by djmaximum17** [jkotlinski/lsdpatch#35]
is there a reason why things like pallets, fonts and kits can't be edited with older LSDJ versions? if I try to load an LSDJ rom image that uses version 3 or older, it throws an empty error message.

**Comment by jkotlinski** [comment]
Hi!
I do not test with such old versions. I think very few use v3 nowadays. As
a workaround, you can try an older lsdpatch version, for example v0.19
which is available in releases.

**Comment by djmaximum17** [comment]
thanks. I've got v19 already and it works fine, and v5, which allows to edit even older versions.

**Comment by jkotlinski** [comment]
Fixed for v1.6.0
