### ISSUE TITLE
Avoid manual sample conversion

### ISSUE THREAD

**Issue by jkotlinski** [jkotlinski/lsdpatch#44]
For non-technical users, it would be great if sox was run automatically, without any need to prepare samples from the command line.

**Comment by Eiyeron** [comment]
I don't know how bundling binary executable would work with lsdj.

Looks like there are wrappers that call the executable itself like [this][sox-wrapper] library

Regarding filtering or resampling, there are some libraries in java or wrapping libresample to do this kind of process, this might alleviate us from many headaches regarding converting ourselves the sample data.

[sox-wrapper]: https://github.com/corballis/sox-wrapper-java

**Comment by jkotlinski** [comment]
I don’t exactly know what is possible, but anything that makes this process
easier is an improvement :-)
Since not everyone knows how to use command line tools.

**Comment by jkotlinski** [comment]
Java AudioSystem also has inbuilt facilities for sample conversion. Maybe
it would be possible to use that to get to 11468 Hz 8-bit. And then
manually dither and convert to 4-bit. I am unsure of quality compared to
sox.

**Comment by Eiyeron** [comment]
I tried to use java's built-in solution but I kept having issues with playback, getting samples cut too soon or having a pop at the end. I think I'm going to need to do some detective work to figure what's really happening for that to be so glitchy.

**Comment by jkotlinski** [comment]
Implemented in Java now.

**Comment by Eiyeron** [comment]
Ah, great, thanks! How does Java's resampler sound like compared to your handmade solution?

**Comment by jkotlinski** [comment]
I dont know but its probably better!
