### ISSUE TITLE
Feature request: 20 Hz highpass on sample import to remove DC offset

### ISSUE THREAD

**Issue by defensem3ch** [jkotlinski/lsdpatch#71]
Samples would likely benefit from an initial HPF to remove DC offset

**Comment by jkotlinski** [comment]
There is DC offset removal already but its done in stupid way, by
calculating average and shifting entire sample up/down

Do you have example of sample that you think would benefit from this?

**Comment by defensem3ch** [comment]
Sure, here are 2 examples
[samples.zip](https://github.com/jkotlinski/lsdpatch/files/6071644/samples.zip)

**Comment by jkotlinski** [comment]
It does not look like those samples have a significant DC offset. I don't think a HPF would help the conversion.

**Comment by defensem3ch** [comment]
Thanks. I tried a few things as well and they are beyond help. I'll close this issue.
